# TermExtractor Configuration

# API Configuration
api:
  # Default Anthropic model to use
  default_model: "claude-3-5-sonnet-20241022"

  # Available models (for UI dropdown)
  available_models:
    - "claude-3-5-sonnet-20241022"
    - "claude-3-5-haiku-20241022"
    - "claude-3-opus-20240229"
    - "claude-3-haiku-20240307"
    - "claude-3-7-sonnet-20250219"

  # API limits and rate limiting
  max_tokens_per_request: 4096
  rate_limit_per_minute: 50
  max_tokens_per_minute: 100000
  timeout_seconds: 300
  max_retries: 4
  retry_backoff_factor: 2  # Exponential backoff: 2s, 4s, 8s, 16s

  # Token management
  token_safety_buffer: 0.9  # Use 90% of limit to be safe
  enable_token_estimation: true
  enable_usage_tracking: true

# Processing Configuration
processing:
  # Batch processing settings
  batch_size: 100  # Segments per batch
  max_batches: null  # null = unlimited
  max_parallel_files: 5
  max_parallel_batches: 3

  # Processing modes
  # Options: "fast" (approximate), "balanced", "detailed" (thorough)
  default_mode: "balanced"

  # Caching
  cache_enabled: true
  cache_ttl_hours: 24
  cache_max_size_mb: 500

  # Checkpoint/resume
  enable_checkpoints: true
  checkpoint_interval_batches: 10

  # Performance optimization
  enable_dynamic_batching: true
  adaptive_batch_sizing: true
  min_batch_size: 20
  max_batch_size: 500

# Extraction Configuration
extraction:
  # Relevance thresholds
  default_relevance_threshold: 70  # 0-100
  min_relevance_threshold: 0
  max_relevance_threshold: 100

  # Term filtering
  min_term_frequency: 2
  max_term_frequency: null  # null = no limit
  min_term_length: 2
  max_term_length: 50

  # Quality tiers
  high_quality_threshold: 80
  medium_quality_threshold: 60

  # Domain classification
  max_domain_depth: 5
  enable_domain_suggestions: true
  domain_confidence_threshold: 0.7

  # Translation
  enable_translation_suggestions: true
  max_translation_alternatives: 5
  translation_confidence_threshold: 0.6

  # Terminology patterns
  extract_multiword_terms: true
  extract_abbreviations: true
  extract_compounds: true
  max_words_in_term: 5

# Language Configuration
languages:
  # Primary supported languages
  supported_languages:
    - en  # English
    - bg  # Bulgarian
    - ro  # Romanian
    - tr  # Turkish
    - de  # German
    - fr  # French
    - es  # Spanish
    - it  # Italian
    - pt  # Portuguese
    - ru  # Russian
    - ar  # Arabic
    - he  # Hebrew
    - zh  # Chinese
    - ja  # Japanese
    - ko  # Korean

  # Language-specific features
  enable_compound_analysis: true  # Germanic languages
  enable_morphological_analysis: true  # Agglutinative languages
  enable_script_detection: true

  # Default language if not specified
  default_source_language: "en"
  default_target_language: null  # null = monolingual mode

# Security Configuration
security:
  # Data protection
  encrypt_storage: true
  encryption_algorithm: "AES-256-GCM"

  # Data retention
  data_retention_days: 7
  auto_cleanup_enabled: true

  # API key management
  store_api_keys: false  # Set to true to enable secure storage
  api_key_encryption: true

  # Privacy
  enable_data_minimization: true
  anonymize_sensitive_data: false

  # Audit logging
  audit_logging: true
  audit_log_retention_days: 90

  # GDPR compliance
  enable_gdpr_features: true
  allow_data_export: true
  allow_data_deletion: true

# Output Configuration
output:
  # Default format
  default_format: "xlsx"

  # Export formats
  supported_formats:
    - "tbx"
    - "xlsx"
    - "csv"
    - "json"
    - "xml"

  # Excel export settings
  excel_include_metadata: true
  excel_create_separate_sheets: true  # All terms vs. high-relevance
  excel_include_statistics: true

  # TBX export settings
  tbx_version: "3.0"
  tbx_include_full_metadata: true
  tbx_xml_declaration: true

  # CSV export settings
  csv_delimiter: ","
  csv_encoding: "utf-8-sig"
  csv_include_header: true

  # Field configuration
  include_fields:
    - "term"
    - "translation"
    - "domain"
    - "pos"
    - "frequency"
    - "relevance_score"
    - "confidence_score"
    - "context"
    - "definition"

# Termbase Configuration
termbase:
  # Supported import formats
  import_formats:
    - "tbx"
    - "xlsx"
    - "csv"
    - "xml"
    - "mtf"
    - "sdltb"

  # Fuzzy matching
  enable_fuzzy_matching: true
  fuzzy_match_threshold: 0.85

  # Verification
  enable_cross_verification: true
  verify_against_multiple: true

  # Conflict resolution
  conflict_resolution_strategy: "newest"  # Options: "newest", "oldest", "manual", "highest_confidence"

# Metadata Configuration
metadata:
  # Metadata categories to collect
  collect_statistical: true
  collect_linguistic: true
  collect_semantic: true
  collect_domain_context: true
  collect_translation: true
  collect_quality: true
  collect_temporal: true
  collect_reference: true
  collect_structural: true
  collect_relationship: true
  collect_usage: true

  # External enrichment
  enable_external_lookups: false  # External dictionaries/glossaries
  external_sources: []

# Evaluation Configuration
evaluation:
  # Metrics
  calculate_precision: true
  calculate_recall: true
  calculate_f1: true

  # Quality scoring
  enable_confidence_scoring: true
  enable_quality_tiering: true

  # Human validation
  enable_validation_interface: true
  validation_sample_size: 100

# UI Configuration
ui:
  # CLI settings
  cli_enable_color: true
  cli_progress_bar_style: "rich"

  # Web UI settings
  web_host: "localhost"
  web_port: 8000
  web_enable_auth: false
  web_theme: "light"

  # Progress visualization
  show_progress_bars: true
  show_time_estimation: true
  show_token_usage: true
  show_cost_estimation: true

# Logging Configuration
logging:
  # Log levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"

  # Log outputs
  log_to_console: true
  log_to_file: true
  log_file_path: "logs/termextractor.log"

  # Log rotation
  log_rotation: "10 MB"
  log_retention: "30 days"

  # Format
  log_format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"

  # Detailed logging
  log_api_calls: true
  log_processing_steps: true
  log_errors_with_traceback: true

# Cost Optimization Configuration
cost_optimization:
  # Monitoring
  enable_cost_tracking: true
  enable_usage_analytics: true

  # Projections
  show_cost_projection: true
  cost_per_1k_tokens: 0.003  # Update based on current pricing

  # Optimization strategies
  enable_smart_caching: true
  enable_batch_optimization: true
  enable_prompt_optimization: true

  # Limits and alerts
  enable_cost_alerts: true
  daily_cost_limit: null  # null = no limit
  monthly_cost_limit: null
  alert_threshold_percentage: 80

# Development Configuration (for testing)
development:
  debug_mode: false
  enable_profiling: false
  mock_api_calls: false
  test_data_dir: "tests/data"
